name: 'Setup tesseract'
description: 'Setting up tesseract'
inputs:
  aws-access-key-id:
    description: Input aws access key id
    required: true
  aws-secret-access-key:
    description: Input aws secret access key

runs:
  using: composite
  steps:
    - name: Install tesseract 5
      shell: bash
      run: |
        sudo apt update
        sudo add-apt-repository -y ppa:alex-p/tesseract-ocr5
        sudo apt install -y tesseract-ocr libtesseract-dev libleptonica-dev pkg-config
    - name: Copy tesseract snum.traineddata from S3
      shell: bash
      run: |
        export AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key-id }}
        export AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}
        aws s3 cp s3://typless-deployment/snum.traineddata snum.traineddata
        sudo mv snum.traineddata /usr/share/tesseract-ocr/5/tessdata/snum.traineddata
        unset AWS_ACCESS_KEY_ID
        unset AWS_SECRET_ACCESS_KEY
