name: 'Code quality'
description: 'Checking code quality'
inputs:
  python-version:
    description: Input python version
    required: true
  uv-version:
    description: Input uv version
    required: true
    default: "0.5.23"
  aws-pypi-username:
    description: Input aws username to access aws pypi bucket
    required: true
  aws-pypi-password:
    description: Input aws password to access aws pypi bucket
    required: true
  working-directory:
    description: Input working directory
    required: true

runs:
  using: composite
  steps:
    - name: Install python dependencies
      uses: typless/actions/install-python-dependencies@v4.0
      with:
        python-version: ${{ inputs.python-version }}
        uv-version: ${{ inputs.uv-version }}
        aws-pypi-username: ${{ inputs.aws-pypi-username }}
        aws-pypi-password: ${{ inputs.aws-pypi-password }}
        working-directory: ${{ inputs.working-directory }}

    - name: Run bandit
      shell: bash
      working-directory:  ${{ inputs.working-directory }}
      run: uv run --no-sync bandit -c pyproject.toml -r .

    - name: Run ruff check
      shell: bash
      working-directory:  ${{ inputs.working-directory }}
      run: uv run --no-sync ruff check

    - name: Check for trivyignore
      id: trivyignore
      shell: bash
      run: |
        if [ -f "${{ inputs.working-directory }}/.trivyignore" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        fi

    - name: Dependency security scan (with ignores)
      if: steps.trivyignore.outputs.exists == 'true'
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: ${{ inputs.working-directory }}
        scanners: vuln
        exit-code: 1
        ignore-unfixed: true
        trivyignores: ${{ inputs.working-directory }}/.trivyignore

    - name: Dependency security scan
      if: steps.trivyignore.outputs.exists != 'true'
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: ${{ inputs.working-directory }}
        scanners: vuln
        exit-code: 1
        ignore-unfixed: true