name: 'Export python dependencies'
description: 'Export python dependencies using poetry'
inputs:
  python-version:
    description: Input python version
    required: true
  poetry-version:
    description: Input poetry version
    required: false
    default: "1.5.1"
  aws-pypi-username:
    description: Input aws username to access aws pypi bucket
    required: true
  aws-pypi-password:
    description: Input aws password to access aws pypi bucket
    required: true
  groups:
    description: Input optional groups to be exported
    required: false
  working-directory:
    description: Input working directory
    required: true

runs:
  using: composite
  steps:
    - name: Set up poetry
      uses: typless/actions/setup-poetry@v3.0
      with:
        python-version: ${{ inputs.python-version }}
        version: ${{ inputs.poetry-version }}
        aws-pypi-username: ${{ inputs.aws-pypi-username }}
        aws-pypi-password: ${{ inputs.aws-pypi-password }}
    - name: Poetry export with optional groups
      if: inputs.groups != ''
      shell: bash
      run: |
        poetry export \
          --without-hashes \
          --with-credentials \
          --with ${{ inputs.groups }} \
          -f requirements.txt \
          -o requirements.txt
      working-directory: ${{ inputs.working-directory }}
    - name: Poetry export without optional groups
      if: inputs.groups == ''
      shell: bash
      run: |
        poetry export \
          --without-hashes \
          --with-credentials \
          -f requirements.txt \
          -o requirements.txt
      working-directory: ${{ inputs.working-directory }}
