name: 'Setup uv'
description: 'Setting up uv'
inputs:
  python-version:
    description: Input python version
    required: true
  version:
    description: Input uv version
    required: true
    default: "0.5.23"
  working-directory:
    description: Input working directory
    required: true

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v8.1.0
      with:
        version: ${{ inputs.version }}
        enable-cache: true
        cache-dependency-glob: "${{ inputs.working-directory }}/uv.lock"
