name: 'Install python dependencies'
description: 'Installation of python dependencies'
inputs:
  python-version:
    description: Input python version
    required: true
  uv-version:
    description: Input uv version
    required: true
    default: "0.5.23"
  aws-pypi-username:
    description: Input aws username to access aws pypi bucket
    required: true
  aws-pypi-password:
    description: Input aws password to access aws pypi bucket
    required: true
  working-directory:
    description: Input working directory
    required: true

runs:
  using: composite
  steps:
    - name: Setup uv
      uses: typless/actions/setup-uv@v4.0
      with:
        python-version: ${{ inputs.python-version }}
        version: ${{ inputs.uv-version }}
        working-directory: ${{ inputs.working-directory }}

    - name: Install the project
      shell: bash
      env:
        UV_INDEX_TYPLESS_USERNAME: ${{ inputs.aws-pypi-username }}
        UV_INDEX_TYPLESS_PASSWORD: ${{ inputs.aws-pypi-password }}
      working-directory: ${{ inputs.working-directory }}
      run: uv sync --frozen
