name: 'Sls deploy'
description: 'Deploying serverless'
inputs:
  node-version:
    description: Input node version
    required: true
  stage:
    description: Stage where to deploy
    required: true
  working-directory:
    description: Input working directory
    required: true

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version}}
        cache: 'yarn'
        cache-dependency-path: ${{ inputs.working-directory }}/yarn.lock
    - run: yarn install --frozen-lockfile
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Deploy
      run: yarn run sls deploy --verbose --stage ${{ inputs.stage }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Serverless doctor
      if: failure()
      run: yarn run serverless doctor
      working-directory: ${{ inputs.working-directory }}
      shell: bash
