name: 'Sls deploy'
description: 'Deploying serverless'
inputs:
  working-dir:
    description: Input working directory
    required: true
  node-version:
    description: Input node version installing
    required: true
  stage:
    description: Stage where to deploy
    required: true
runs:

  using: composite
  steps:
      working-directory: ${{ inputs.working-dir }}
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version}}
        cache: 'yarn'
        cache-dependency-path: ${{ inputs.working-dir }}/yarn.lock
    - run: yarn install --frozen-lockfile
      working-directory: ${{ inputs.working-dir }}
      shell: bash
    - name: Deploy
      run: yarn run sls deploy --verbose --stage  ${{ inputs.stage }}
      working-directory: ${{ inputs.working-dir }}
      shell: bash
