name: 'Run Tests'
description: 'Runnning tests'
inputs:
  python-version:
    description: Input python version installing
    required: true
    default: '3.9'
  aws-username:
    description: Input aws username to access aws bucket
    required: true
  aws-password:
    description: Input aws password to access aws bucket
  working-dir:
    description: input working directory
    required: true
  test-args:
    description: Arguments added to pytest
    required: true
runs:

  using: composite
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
    - name: Run config token
      shell: bash
      run: poetry config http-basic.typless ${{ inputs.aws-username }} ${{ inputs.aws-password }}
    - name: Install dependencies
      shell: bash
      run: poetry install
      working-directory: ${{ inputs.working-dir }}
    - name: Run tests
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: poetry run pytest ${{ inputs.test-args }}
